!
!  This file is part of MUMPS 5.6.2, released
!  on Wed Oct 11 09:36:25 UTC 2023
!
!
!  Copyright 1991-2023 CERFACS, CNRS, ENS Lyon, INP Toulouse, Inria,
!  Mumps Technologies, University of Bordeaux.
!
!  This version of MUMPS is provided to you free of charge. It is
!  released under the CeCILL-C license 
!  (see doc/CeCILL-C_V1-en.txt, doc/CeCILL-C_V1-fr.txt, and
!  https://cecill.info/licences/Licence_CeCILL-C_V1-en.html)
!
!
!     Stub mpif.h file including symbols used by MUMPS.
!
      INTEGER(4) MPI_2DOUBLE_PRECISION
      INTEGER(4) MPI_2INTEGER
      INTEGER(4) MPI_2REAL
      INTEGER(4) MPI_ANY_SOURCE
      INTEGER(4) MPI_ANY_TAG
      INTEGER(4) MPI_BYTE
      INTEGER(4) MPI_CHARACTER
      INTEGER(4) MPI_COMM_NULL
      INTEGER(4) MPI_COMM_WORLD
      INTEGER(4) MPI_COMPLEX
      INTEGER(4) MPI_DOUBLE_COMPLEX
      INTEGER(4) MPI_DOUBLE_PRECISION
      INTEGER(4) MPI_INTEGER
      INTEGER(4) MPI_LOGICAL
      INTEGER(4) MPI_MAX
      INTEGER(4) MPI_MAX_PROCESSOR_NAME
      INTEGER(4) MPI_MAXLOC
      INTEGER(4) MPI_MIN
      INTEGER(4) MPI_MINLOC
      INTEGER(4) MPI_PACKED
      INTEGER(4) MPI_PROD
      INTEGER(4) MPI_REAL
      INTEGER(4) MPI_REPLACE
      INTEGER(4) MPI_REQUEST_NULL
      INTEGER(4) MPI_SOURCE
      INTEGER(4) MPI_STATUS_SIZE
      INTEGER(4) MPI_SUM
      INTEGER(4) MPI_TAG
      INTEGER(4) MPI_UNDEFINED
      INTEGER(4) MPI_WTIME_IS_GLOBAL
      INTEGER(4) MPI_LOR
      INTEGER(4) MPI_LAND
      INTEGER(4) MPI_INTEGER8
      INTEGER(4) MPI_REAL8
      INTEGER(4) MPI_COMM_SELF
      INTEGER(4) MPI_BSEND_OVERHEAD
      INTEGER(4) MPI_THREAD_SINGLE
      INTEGER(4) MPI_THREAD_FUNNELED
      INTEGER(4) MPI_THREAD_MULTIPLE
      INTEGER(4) MPI_BOR
      INTEGER(4) MPI_WIN_NULL
      INTEGER(4) MPI_ADDRESS_KIND
      INTEGER(4) MPI_INFO_NULL
      INTEGER(4) MPI_SUCCESS
      INTEGER(4) MPI_ERRORS_RETURN
      PARAMETER (MPI_2DOUBLE_PRECISION=1)
      PARAMETER (MPI_2INTEGER=2)
      PARAMETER (MPI_2REAL=3)
      PARAMETER (MPI_ANY_SOURCE=4)
      PARAMETER (MPI_ANY_TAG=5)
      PARAMETER (MPI_BYTE=6)
      PARAMETER (MPI_CHARACTER=7)
      PARAMETER (MPI_COMM_NULL=8)
      PARAMETER (MPI_COMM_WORLD=9)
      PARAMETER (MPI_COMPLEX=10)
      PARAMETER (MPI_DOUBLE_COMPLEX=11)
      PARAMETER (MPI_DOUBLE_PRECISION=12)
      PARAMETER (MPI_INTEGER=13)
      PARAMETER (MPI_LOGICAL=14)
      PARAMETER (MPI_MAX=15)
      PARAMETER (MPI_MAX_PROCESSOR_NAME=31)
      PARAMETER (MPI_MAXLOC=16)
      PARAMETER (MPI_MIN=17)
      PARAMETER (MPI_MINLOC=18)
      PARAMETER (MPI_PACKED=19)
      PARAMETER (MPI_PROD=20)
      PARAMETER (MPI_REAL=21)
      PARAMETER (MPI_REPLACE=22)
      PARAMETER (MPI_REQUEST_NULL=23)
      PARAMETER (MPI_SOURCE=1)
      PARAMETER (MPI_STATUS_SIZE=2)
      PARAMETER (MPI_SUM=26)
      PARAMETER (MPI_TAG=2)
      PARAMETER (MPI_UNDEFINED=28)
      PARAMETER (MPI_WTIME_IS_GLOBAL=30)
      PARAMETER (MPI_LOR=31)
      PARAMETER (MPI_LAND=32)
      PARAMETER (MPI_INTEGER8=33)
      PARAMETER (MPI_REAL8=34)
      PARAMETER (MPI_COMM_SELF=35)
      PARAMETER (MPI_THREAD_SINGLE=36)
      PARAMETER (MPI_THREAD_FUNNELED=37)
      PARAMETER (MPI_THREAD_MULTIPLE=38)
      PARAMETER (MPI_BOR=39)
      PARAMETER (MPI_WIN_NULL=40)
      PARAMETER (MPI_ADDRESS_KIND=8)
      PARAMETER (MPI_INFO_NULL=41)
      PARAMETER (MPI_SUCCESS=0)
      PARAMETER (MPI_ERRORS_RETURN=42)

      INTEGER(4) MPI_IN_PLACE
      COMMON/mpif_libseq/MPI_IN_PLACE

      PARAMETER (MPI_BSEND_OVERHEAD=0)
      DOUBLE PRECISION MPI_WTIME
      EXTERNAL MPI_WTIME
